from app.schemas.template import PostTemplate

TEMPLATES = [
  PostTemplate(
    id="insight",
    name="Industry Insight",
    description="Turns the article into an insightful, thought-leadership post with key takeaways.",
    prompt="Summarize the article with deep industry insights, 3 key takeaways, and a thought-provoking question.",
    hashtags=["#IndustryInsight", "#Leadership", "#KeyTakeaways", "#FutureOfWork"],
    cta="Share your thoughts in the comments!",
    hook_required=True,
    include_article_link=True,
    hashtag_count=8,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Professional but engaging, emphasize authority, credibility, and forward-looking perspective."
  ),
  PostTemplate(
    id="story",
    name="Storytelling",
    description="Turns the article into a narrative-style post.",
    prompt="Transform the article into a captivating LinkedIn story with a strong hook, emotional build-up, and memorable ending.",
    hashtags=["#Storytelling", "#Narrative", "#LinkedInStories", "#BrandStory"],
    cta="Have a similar story? Comment below!",
    hook_required=True,
    include_article_link=True,
    hashtag_count=8,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Conversational, relatable, and vivid imagery that emotionally connects with the audience."
  ),
  PostTemplate(
    id="debate",
    name="Debate & Engagement",
    description="Generates a provocative post that invites discussion.",
    prompt="Summarize the article with a controversial angle and invite readers to share their stance.",
    hashtags=["#Debate", "#Engagement", "#Discussion", "#DifferentPerspectives"],
    cta="Do you agree or disagree? Let us know!",
    hook_required=True,
    include_article_link=True,
    hashtag_count=8,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Bold, slightly provocative but respectful, encouraging multiple perspectives."
  ),
  PostTemplate(
    id="howto",
    name="How-To & Tips",
    description="Turns the article into a practical, step-by-step tips post.",
    prompt="Extract 5 actionable tips from the article, each with a short, clear explanation.",
    hashtags=["#HowTo", "#Productivity", "#CareerTips", "#ActionableAdvice"],
    cta="Which of these tips will you try first?",
    hook_required=True,
    include_article_link=True,
    hashtag_count=6,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Clear, concise, and instructional. Focus on practical takeaways."
  ),
  PostTemplate(
    id="data",
    name="Data-Driven",
    description="Focuses on statistics, data points, and research findings from the article.",
    prompt="Present 3-4 key statistics from the article, explain their significance, and ask readers for their interpretation.",
    hashtags=["#DataDriven", "#Research", "#Statistics", "#Insights"],
    cta="What do these numbers tell you?",
    hook_required=True,
    include_article_link=True,
    hashtag_count=6,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Evidence-focused, analytical, and insight-driven with a professional tone."
  ),
  PostTemplate(
    id="listicle",
    name="Listicle",
    description="Summarizes the article as a numbered list of main points.",
    prompt="Present the main points of the article as a short, engaging list.",
    hashtags=["#Listicle", "#QuickRead", "#Takeaways", "#ContentSummary"],
    cta="Which point stands out most to you?",
    hook_required=True,
    include_article_link=True,
    hashtag_count=6,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Easy-to-read, snappy, and skimmable. Use numbered or bullet format."
  ),
  PostTemplate(
    id="trend",
    name="Trend Spotlight",
    description="Highlights a trending topic or emerging idea from the article.",
    prompt="Explain the trend discussed in the article, why it's important, and its potential impact.",
    hashtags=["#Trends", "#Future", "#Innovation", "#MarketShift"],
    cta="Do you see this trend in your industry?",
    hook_required=True,
    include_article_link=True,
    hashtag_count=6,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Timely, forward-thinking, and engaging. Emphasize relevance and opportunity."
  ),
  PostTemplate(
    id="motivational",
    name="Motivational & Inspirational",
    description="Turns the article into an uplifting, motivational post.",
    prompt="Extract an inspiring message from the article, with a strong call-to-action for personal growth.",
    hashtags=["#Motivation", "#Inspiration", "#GrowthMindset", "#Leadership"],
    cta="Tag someone who needs to hear this today!",
    hook_required=True,
    include_article_link=True,
    hashtag_count=6,
    detect_tone=True,
    generate_human_post=True,
    select_best_image=True,
    style_guidelines="Positive, uplifting, and empowering. Use inspiring language and emotional appeal."
  )
]
